### ISSUE TITLE
Add some stateful Action on the Promotion Model

### ISSUE THREAD

**Issue by ahbbzong** [NYU-Devops2021-Promotion/promotions#34]
**As a developer ...  
**I need to Action for a promotion that is able to change...  
**So that I need to add some stateful attributes for the promotion Model

**Details & Assumptions:** 
Add a promotion attribute like "visible/display" for the promotion model to show the current state of a promotion.

**Acceptance Criteria:**
There is a state attribute for each promotion.

```gherkin
Given a promotion model.
When reading the attribute of a promotion.
Then make sure we have an attribute to show its state.
```

**Comment by MitaliO** [comment]
By state, you mean whether a promotion is currently active or not? We can have a flag called enable or is_active and store boolean values. Let me know what you think.

**Comment by HerlinHe** [comment]
Sorry, I don't get what the "state" means. Do you mean the availability? We already have a function to check the availability. And I don't think it is necessary to set it as an attribute because we won't check the status of each promotion every day. In this case, the availability is useless, we can get the availability result using the current attributes "from_date" and "to_date".
